language: ruby
before_install:
  - gem install bundler
before_script:
  - rake db:migrate
script:
  - rake ci
rvm:
   - 2.2.2
   - 2.4.1
   - 2.5.1
gemfile:
  - test/gemfiles/Gemfile.rails.5.2
branches:
  only:
    - master
matrix:
  fast_finish: true
  include:
    - rvm: 2.4.1
      gemfile: test/gemfiles/Gemfile.rails.master
  allow_failures:
    - gemfile: test/gemfiles/Gemfile.rails.master