source "http://rubygems.org"

gemspec

gem "kaminari"

group :development do
  gem "web-console"
  gem "listen"
  gem "rubocop", "~> 0.51.0", require: false
end

group :test do
  gem "rails-controller-testing"
  gem "sqlite3"
  gem "mocha",      require: false
  gem "coveralls",  require: false
end
