# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sofa_blog}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jack Neto", "The Working Group Inc"]
  s.date = %q{2011-02-27}
  s.description = %q{}
  s.email = %q{jack@theworkinggroup.ca}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".DS_Store",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/.DS_Store",
    "app/controllers/cms_admin/blog_comments_controller.rb",
    "app/controllers/cms_admin/blog_posts_controller.rb",
    "app/models/blog_comment.rb",
    "app/models/blog_post.rb",
    "app/models/blog_tag.rb",
    "app/models/blog_tagging.rb",
    "app/views/.DS_Store",
    "app/views/cms_admin/blog_comments/_blog_comment.html.erb",
    "app/views/cms_admin/blog_comments/_form.html.erb",
    "app/views/cms_admin/blog_comments/_status.html.erb",
    "app/views/cms_admin/blog_comments/approve.rjs",
    "app/views/cms_admin/blog_comments/disapprove.rjs",
    "app/views/cms_admin/blog_comments/edit.html.erb",
    "app/views/cms_admin/blog_comments/index.html.erb",
    "app/views/cms_admin/blog_comments/new.html.erb",
    "app/views/cms_admin/blog_posts/_blog_post.html.erb",
    "app/views/cms_admin/blog_posts/_form.html.erb",
    "app/views/cms_admin/blog_posts/edit.html.erb",
    "app/views/cms_admin/blog_posts/index.html.erb",
    "app/views/cms_admin/blog_posts/new.html.erb",
    "app/views/sofa_blog/_head.html.erb",
    "app/views/sofa_blog/_nav.html.erb",
    "config/.DS_Store",
    "config/routes.rb",
    "db/migrate/01_create_sofa_blog.rb",
    "doc/sofa.png",
    "lib/generators/README",
    "lib/generators/blog_generator.rb",
    "lib/sofa_blog.rb",
    "lib/sofa_blog/engine.rb",
    "public/javascripts/jquery.autocomplete.pack.js",
    "public/stylesheets/content.css",
    "sofa_blog.gemspec",
    "tmp/application.rb",
    "tmp/boot.rb",
    "tmp/environment.rb",
    "tmp/initializers/formatted_form_builder.rb",
    "tmp/initializers/wristband.rb"
  ]
  s.homepage = %q{http://github.com/twg/sofa-blog}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A blog extension for Comfortable Mexican Sofa}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<comfortable_mexican_sofa>, [">= 1.0.46"])
      s.add_runtime_dependency(%q<comfortable_mexican_sofa>, [">= 1.0.46"])
    else
      s.add_dependency(%q<comfortable_mexican_sofa>, [">= 1.0.46"])
      s.add_dependency(%q<comfortable_mexican_sofa>, [">= 1.0.46"])
    end
  else
    s.add_dependency(%q<comfortable_mexican_sofa>, [">= 1.0.46"])
    s.add_dependency(%q<comfortable_mexican_sofa>, [">= 1.0.46"])
  end
end

