# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sofa_blog}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jack Neto", "The Working Group Inc."]
  s.date = %q{2011-10-18}
  s.description = %q{}
  s.email = %q{jack@theworkinggroup.ca}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/assets/images/rails.png",
    "app/assets/javascripts/sofa_blog/application.js",
    "app/assets/javascripts/sofa_blog/jquery.autocomplete.js",
    "app/assets/javascripts/sofa_blog/posts.js",
    "app/assets/stylesheets/sofa_blog/admin.css",
    "app/assets/stylesheets/sofa_blog/application.css",
    "app/assets/stylesheets/sofa_blog/reset.css",
    "app/controllers/application_controller.rb",
    "app/controllers/sofa_blog/admin/base_controller.rb",
    "app/controllers/sofa_blog/admin/comments_controller.rb",
    "app/controllers/sofa_blog/admin/posts_controller.rb",
    "app/controllers/sofa_blog/posts_controller.rb",
    "app/helpers/sofa_blog/posts_helper.rb",
    "app/helpers/sofa_blog_helper.rb",
    "app/models/.gitkeep",
    "app/models/sofa_blog/comment.rb",
    "app/models/sofa_blog/post.rb",
    "app/models/sofa_blog/tag.rb",
    "app/models/sofa_blog/tagging.rb",
    "app/views/layouts/application.html.erb",
    "app/views/sofa_blog/admin/_html_head.html.erb",
    "app/views/sofa_blog/admin/_navigation.html.erb",
    "app/views/sofa_blog/admin/comments/_comment.html.erb",
    "app/views/sofa_blog/admin/comments/_form.html.erb",
    "app/views/sofa_blog/admin/comments/_status.html.erb",
    "app/views/sofa_blog/admin/comments/approve.js.erb",
    "app/views/sofa_blog/admin/comments/disapprove.js.erb",
    "app/views/sofa_blog/admin/comments/edit.html.erb",
    "app/views/sofa_blog/admin/comments/index.html.erb",
    "app/views/sofa_blog/admin/comments/new.html.erb",
    "app/views/sofa_blog/admin/posts/_form.html.erb",
    "app/views/sofa_blog/admin/posts/_post.html.erb",
    "app/views/sofa_blog/admin/posts/edit.html.erb",
    "app/views/sofa_blog/admin/posts/index.html.erb",
    "app/views/sofa_blog/admin/posts/new.html.erb",
    "app/views/sofa_blog/posts/_post.html.erb",
    "app/views/sofa_blog/posts/index.html.erb",
    "config.ru",
    "config/application.rb",
    "config/boot.rb",
    "config/database.yml",
    "config/environment.rb",
    "config/environments/development.rb",
    "config/environments/production.rb",
    "config/environments/test.rb",
    "config/initializers/secret_token.rb",
    "config/initializers/sofa_blog.rb",
    "config/initializers/wrap_parameters.rb",
    "config/locales/en.yml",
    "config/routes.rb",
    "db/migrate/01_create_sofa_blog.rb",
    "db/schema.rb",
    "db/seeds.rb",
    "lib/generators/README",
    "lib/generators/blog_generator.rb",
    "lib/sofa_blog.rb",
    "lib/sofa_blog/configuration.rb",
    "lib/sofa_blog/engine.rb",
    "lib/sofa_blog/form_builder.rb",
    "script/rails",
    "sofa_blog.gemspec",
    "test/fixtures/.gitkeep",
    "test/fixtures/sofa_blog/comments.yml",
    "test/fixtures/sofa_blog/posts.yml",
    "test/functional/.gitkeep",
    "test/functional/sofa_blog/admin/comments_controller_test.rb",
    "test/functional/sofa_blog/admin/posts_controller_test.rb",
    "test/functional/sofa_blog/posts_controller_test.rb",
    "test/test_helper.rb",
    "test/unit/.gitkeep",
    "test/unit/comment_test.rb",
    "test/unit/helpers/sofa_blog/posts_helper_test.rb",
    "test/unit/post_test.rb",
    "test/unit/tag_test.rb",
    "test/unit/tagging_test.rb"
  ]
  s.homepage = %q{http://github.com/twg/sofa-blog}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{SofaBlog is a blog engine for Rails 3.1 apps (and ComfortableMexicanSofa)}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.1.0"])
      s.add_runtime_dependency(%q<rinku>, [">= 1.2.2"])
      s.add_runtime_dependency(%q<jquery-rails>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 3.1.0"])
      s.add_dependency(%q<rinku>, [">= 1.2.2"])
      s.add_dependency(%q<jquery-rails>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.1.0"])
    s.add_dependency(%q<rinku>, [">= 1.2.2"])
    s.add_dependency(%q<jquery-rails>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

